### ISSUE TITLE
Problem with BluetoothConnector

### ISSUE THREAD

**Issue by icelord75** [tcely/cliutils#1]
Failed to Run with:
BluetoothConnector
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: BluetoothConnector
  Reason: image not found
Abort trap: 6

try to static link it for current xcode libs - failed too:
./BluetoothConnector
dyld: lazy symbol binding failed: Symbol not found: __T0s11CommandLineO9argumentsSaySSGvau
  Referenced from: BluetoothConnector
  Expected in: /System/Library/PrivateFrameworks/Swift/libswiftCore.dylib

dyld: Symbol not found: __T0s11CommandLineO9argumentsSaySSGvau
  Referenced from: BluetoothConnector
  Expected in: /System/Library/PrivateFrameworks/Swift/libswiftCore.dylib

Abort trap: 6

**Comment by tcely** [comment]
Try compiling your own binary from: https://github.com/lapfelix/BluetoothConnector

**Comment by icelord75** [comment]
now it's OK!
